import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import Container from "../components/common/Container";

import {
  getAnalysis,
} from "../services/analysisService";

import ProjectCard from "../components/dashboard/ProjectCard";
import StatisticsCard from "../components/dashboard/StatisticsCard";
import StatusCard from "../components/dashboard/StatusCard";


export default function Dashboard() {
  const { projectId } = useParams();

  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!projectId) {
      setError("Project ID is missing.");
      setLoading(false);
      return;
    }

    let intervalId;
    let isCancelled = false;

    async function loadAnalysis() {
      try {
        const data = await getAnalysis(projectId);

        if (isCancelled) {
          return;
        }

        console.log("Analysis:", data);

        setAnalysis(data);
        setError("");
        setLoading(false);

        if (
          data.status === "completed" ||
          data.status === "failed"
        ) {
          clearInterval(intervalId);
        }

      } catch (requestError) {
        if (isCancelled) {
          return;
        }

        const status =
          requestError.response?.status;

        if (status === 404) {
          setError(
            "Analysis has not been started for this project."
          );
        } else {
          setError(
            requestError.response?.data?.detail ||
            requestError.message ||
            "Failed to load the analysis."
          );
        }

        setLoading(false);
      }
    }

    loadAnalysis();

    intervalId = setInterval(
      loadAnalysis,
      2000
    );

    return () => {
      isCancelled = true;
      clearInterval(intervalId);
    };
  }, [projectId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <h2 className="text-2xl font-semibold">
          Loading AI Analysis...
        </h2>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center px-6">
        <div className="max-w-xl rounded-2xl border border-red-200 bg-red-50 p-6 text-center">
          <h2 className="text-2xl font-semibold text-red-700">
            Unable to load analysis
          </h2>

          <p className="mt-3 text-red-600">
            {error}
          </p>
        </div>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <h2 className="text-2xl font-semibold">
          Analysis not found.
        </h2>
      </div>
    );
  }

  return (
    <section className="py-20 bg-slate-50 min-h-screen">
      <Container>
        <div className="mb-12">
          <h1 className="text-5xl font-bold">
            AI Analysis Dashboard
          </h1>

          <p className="text-slate-500 mt-3">
            Review your architectural design analysis generated by GreenScape AI.
          </p>
        </div>

        <div className="mb-8 rounded-2xl bg-white p-6 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-sm text-slate-500">
                Current stage
              </p>

              <p className="text-xl font-semibold">
                {analysis.current_stage}
              </p>
            </div>

            <div>
              <p className="text-sm text-slate-500">
                Status
              </p>

              <p className="text-xl font-semibold capitalize">
                {analysis.status}
              </p>
            </div>

            <div>
              <p className="text-sm text-slate-500">
                Progress
              </p>

              <p className="text-xl font-semibold">
                {analysis.progress ?? 0}%
              </p>
            </div>
          </div>

          <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-200">
            <div
              className="h-full bg-green-600 transition-all duration-500"
              style={{
                width: `${analysis.progress ?? 0}%`,
              }}
            />
          </div>
        </div>

        {analysis.error_message && (
          <div className="mb-8 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-700">
            {analysis.error_message}
          </div>
        )}

        <div className="grid lg:grid-cols-3 gap-8">
          <ProjectCard
            project={buildProjectData(analysis)}
          />

          <StatisticsCard
            analysis={buildStatisticsData(analysis)}
          />

          <StatusCard
            analysis={analysis}
          />
        </div>
      </Container>
    </section>
  );
}


function buildProjectData(analysis) {
  const projectData =
    analysis.design_analysis?.project_data || {};

  return {
    name:
      projectData.project_name ||
      "Untitled Project",

    building_type:
      projectData.building_type ||
      "Not specified",

    location:
      projectData.location ||
      "Not specified",

    floor_area:
      projectData.area != null
        ? `${projectData.area} m²`
        : "Not specified",

    floors:
      projectData.floors ??
      "Not specified",
  };
}


function buildStatisticsData(analysis) {
  const visionTotals =
    analysis.vision_result?.totals || {};

  return {
    overall_score:
      analysis.overall_score ?? 0,

    scores: {
      architecture:
        analysis.architecture_result?.score ?? 0,

      sustainability:
        analysis.sustainability_result?.score ?? 0,

      energy:
        analysis.energy_result?.score ?? 0,

      lighting:
        analysis.lighting_result?.score ?? 0,

      ventilation:
        analysis.ventilation_result?.score ?? 0,

      accessibility:
        analysis.accessibility_result?.score ?? 0,

      building_code:
        analysis.building_code_result?.score ?? 0,

      cost:
        analysis.cost_result?.score ?? 0,
    },

    vision_totals: {
      rooms: visionTotals.rooms ?? 0,
      walls: visionTotals.walls ?? 0,
      doors: visionTotals.doors ?? 0,
      windows: visionTotals.windows ?? 0,
      texts: visionTotals.texts ?? 0,
    },
  };
}